package model.pojo;
// Generated Sep 22, 2017 10:41:01 AM by Hibernate Tools 4.3.1



/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {

    private int id;
    private String firstName;
    private String lastName;

    public Actor() {
    }
    public Actor(int id) {
        this.id = id;
    }
    public Actor(int id, String firstName, String lastName) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


